name: Capitalium
version: '${version}'
main: capitaliul.capitalium.Capitalium
api-version: 1.19
authors: [ vultorio ]
commands:
  kit:
    description: Your description
    usage: /<command>
    permission: capitalium.kit

